
# REQUEST
#===============================================================================
Header header

# 2D points representing two diagonally opposite corners of the 2D region of interest
# (the first element of the array = X-coord, the second = Y-coord)
int16[2] p1
int16[2] p2

# Estimation mode {1, 2, 3} - if it is not specified, the default value = 1
int8 mode
---

# RESPONSE
#===============================================================================
# 3D points representing the corners of the resulting bounding box
# (the first element of the array = X-coord, the second = Y-coord, the third = Z-coord)
float32[3] p1
float32[3] p2
float32[3] p3
float32[3] p4
float32[3] p5
float32[3] p6
float32[3] p7
float32[3] p8

# pose includes a position and an orientation of the resulting bounding box
geometry_msgs/Pose pose

# scale includes a size of the bounding box in direction of X, Y and Z coordinates
# (before rotation given by orientation, which is included in pose)
geometry_msgs/Vector3 scale

